controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    torque_controller:
      type: effort_controllers/JointGroupEffortController

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    gripper_position_controller:
      type: position_controllers/GripperActionController
      
      


position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

torque_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

#####################################
# INTENTO
gripper_position_controller:
  ros__parameters:
    joint: 'jointGripper'
    # max_effort: 30.0                # máximo torque que puede aplicar
    # action_monitor_rate: 20.0
    # goal_tolerance: 0.01
    # allow_stalling: false
    # stall_velocity_threshold: 0.001
    # stall_timeout: 1.0
#########################################

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
